apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: wordpress
  namespace: default
spec:
  releaseName: wordpress
  chart:
    spec:
     chart: ../charts/wordpress
  interval: 1m
  values:
    mariadb:
      auth:
        rootPassword: admin
        username: admin
        password: admin
        database: wordpress
    wordpressUsername: admin
    wordpressPassword: admin123
    service:
      type: NodePort
      nodePorts:
        http: 30080
