apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: wordpress
  namespace: default
spec:
  releaseName: wordpress
  chart:
    spec:
      chart: wordpress
      version: "18.0.0" 
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
  interval: 1m
  valuesFrom:
    - kind: ConfigMap
      name: wordpress-values
